import { map } from 'ramda';
import * as Bodies from './bodies.ts';

const CDN_URL = 'https://atlasofspace.b-cdn.net';
const IMAGE_FILENAMES = {
  arrokothAnimationSrc: 'arrokoth-rotation.gif',
  arrokothSrc: 'arrokoth-thumb.jpg',
  bennuLandingSrc: 'bennu-landing.jpg',
  bennuRotationSrc: 'bennu-rotation.gif',
  bennuSurfaceSrc: 'bennu-surface.jpg',
  bennuSrc: 'bennu-thumb.png',
  callistoSrc: 'callisto-thumb.jpg',
  ceresTextureSrc: 'ceres-texture.jpg',
  ceresSrc: 'ceres-thumb.jpg',
  cg67pAnimationSrc: 'cg67p-animation.gif',
  cg57pSrc: 'cg67p-thumb.jpg',
  cg67pThumb2Src: 'cg67p-thumb2.jpg',
  cg67pThumb3Src: 'cg67p-thumb3.jpg',
  deimosSrc: 'deimos-thumb.jpg',
  earthTextureSrc: 'earth-texture.jpg',
  earthSrc: 'earth-thumb.jpg',
  erosSrc: 'eros-thumb.jpg',
  europaSrc: 'europa-thumb.jpg',
  farfaroutSrc: 'farfarout-thumb.gif',
  firmamentTextureSrc: 'firmament.jpg',
  ganymedeSrc: 'ganymede-thumb.jpg',
  hygieaSrc: 'hygiea-thumb.jpg',
  ioSrc: 'io-thumb.jpg',
  junoSrc: 'juno-thumb.jpg',
  jupiterTextureSrc: 'jupiter-texture.jpg',
  jupiterSrc: 'jupiter-thumb.jpg',
  lunaTextureSrc: 'luna-texture.jpg',
  lunaSrc: 'luna-thumb.jpg',
  lutetiaSrc: 'lutetia-thumb.jpg',
  makemakeSrc: 'makemake-thumb.jpg',
  marsCuriositySrc: 'mars-curiosity.jpg',
  marsKorolevSrc: 'mars-korolev.jpg',
  marsTextureSrc: 'mars-texture.jpg',
  marsSrc: 'mars-thumb.jpg',
  marsVikingSrc: 'mars-viking.jpg',
  mathildeSrc: 'mathilde-thumb.jpg',
  mercuryTextureSrc: 'mercury-texture.jpg',
  mercurySrc: 'mercury-thumb.jpg',
  mimasSrc: 'mimas-thumb.jpg',
  neptuneTextureSrc: 'neptune-texture.jpg',
  neptuneSrc: 'neptune-thumb.jpg',
  nereusSrc: 'nereus-thumb.gif',
  pallasSrc: 'pallas-thumb.jpg',
  phobosSrc: 'phobos-thumb.jpg',
  plutoSrc: 'pluto-thumb.jpg',
  psycheIllustrationSrc: 'psyche-illustration.jpg',
  psycheMissionIllustrationSrc: 'psyche-mission-illustration.jpg',
  ryuguRotationSrc: 'ryugu-rotation.gif',
  ryuguSurfaceSrc: 'ryugu-surface.jpg',
  ryuguSurface2Src: 'ryugu-surface2.jpg',
  ryuguSrc: 'ryugu-thumb.jpg',
  saturnRingsTextureSrc: 'saturn-rings-texture.png',
  saturnTextureSrc: 'saturn-texture.jpg',
  saturnSrc: 'saturn-thumb.jpg',
  solTextureSrc: 'sol-texture.jpg',
  solSrc: 'sol-thumb.jpg',
  uranusTextureSrc: 'uranus-texture.jpg',
  uranusSrc: 'uranus-thumb.jpg',
  venusMagellanSrc: 'venus-magellan.jpg',
  venusTextureSrc: 'venus-texture.jpg',
  venusSrc: 'venus-thumb.jpg',
  venusVeneraSrc: 'venus-venera.jpg',
  venusVenera2Src: 'venus-venera2.jpg',
  vestaSrc: 'vesta-thumb.jpg',
};
const IMAGE_URLS = map(filename => `${CDN_URL}/${filename}`, IMAGE_FILENAMES);

export const Thumbnails: Record<string, string> = {
  [Bodies.SOL.name]: IMAGE_URLS.solSrc,
  [Bodies.MERCURY.name]: IMAGE_URLS.mercurySrc,
  [Bodies.VENUS.name]: IMAGE_URLS.venusSrc,
  [Bodies.EARTH.name]: IMAGE_URLS.earthSrc,
  [Bodies.LUNA.name]: IMAGE_URLS.lunaSrc,
  [Bodies.MARS.name]: IMAGE_URLS.marsSrc,
  [Bodies.PHOBOS.name]: IMAGE_URLS.phobosSrc,
  [Bodies.DEIMOS.name]: IMAGE_URLS.deimosSrc,
  [Bodies.JUPITER.name]: IMAGE_URLS.jupiterSrc,
  [Bodies.IO.name]: IMAGE_URLS.ioSrc,
  [Bodies.EUROPA.name]: IMAGE_URLS.europaSrc,
  [Bodies.GANYMEDE.name]: IMAGE_URLS.ganymedeSrc,
  [Bodies.CALLISTO.name]: IMAGE_URLS.callistoSrc,
  [Bodies.SATURN.name]: IMAGE_URLS.saturnSrc,
  [Bodies.MIMAS.name]: IMAGE_URLS.mimasSrc,
  [Bodies.URANUS.name]: IMAGE_URLS.uranusSrc,
  [Bodies.NEPTUNE.name]: IMAGE_URLS.neptuneSrc,
  [Bodies.PLUTO.name]: IMAGE_URLS.plutoSrc,
  [Bodies.CERES.name]: IMAGE_URLS.ceresSrc,
  [Bodies.PALLAS.name]: IMAGE_URLS.pallasSrc,
  [Bodies.VESTA.name]: IMAGE_URLS.vestaSrc,
  [Bodies.HYGIEA.name]: IMAGE_URLS.hygieaSrc,
  [Bodies.JUNO.name]: IMAGE_URLS.junoSrc,
  [Bodies.CG67P.name]: IMAGE_URLS.cg57pSrc,
  [Bodies.RYUGU.name]: IMAGE_URLS.ryuguSrc,
  [Bodies.BENNU.name]: IMAGE_URLS.bennuSrc,
  [Bodies.LUTETIA.name]: IMAGE_URLS.lutetiaSrc,
  [Bodies.NEREUS.name]: IMAGE_URLS.nereusSrc,
  [Bodies.MAKEMAKE.name]: IMAGE_URLS.makemakeSrc,
  [Bodies.EROS.name]: IMAGE_URLS.erosSrc,
  [Bodies.MATHILDE.name]: IMAGE_URLS.mathildeSrc,
  [Bodies.ARROKOTH.name]: IMAGE_URLS.arrokothSrc,
  [Bodies.FARFAROUT.name]: IMAGE_URLS.farfaroutSrc,
} as const;

export const GalleryImages: Record<string, Array<string>> = {
  [Bodies.MARS.name]: [IMAGE_URLS.marsKorolevSrc, IMAGE_URLS.marsVikingSrc, IMAGE_URLS.marsCuriositySrc],
  [Bodies.CG67P.name]: [IMAGE_URLS.cg67pAnimationSrc, IMAGE_URLS.cg67pThumb2Src, IMAGE_URLS.cg67pThumb3Src],
  [Bodies.VENUS.name]: [IMAGE_URLS.venusVeneraSrc, IMAGE_URLS.venusVenera2Src, IMAGE_URLS.venusMagellanSrc],
  [Bodies.ARROKOTH.name]: [IMAGE_URLS.arrokothAnimationSrc],
  [Bodies.BENNU.name]: [IMAGE_URLS.bennuLandingSrc, IMAGE_URLS.bennuRotationSrc, IMAGE_URLS.bennuSurfaceSrc],
  [Bodies.RYUGU.name]: [IMAGE_URLS.ryuguSurfaceSrc, IMAGE_URLS.ryuguSurface2Src, IMAGE_URLS.ryuguRotationSrc],
  [Bodies.PSYCHE.name]: [IMAGE_URLS.psycheIllustrationSrc, IMAGE_URLS.psycheMissionIllustrationSrc],
} as const;

export const Textures: Record<string, string> = {
  FIRMAMENT: IMAGE_URLS.firmamentTextureSrc,
  [Bodies.SOL.name]: IMAGE_URLS.solTextureSrc,
  [Bodies.MERCURY.name]: IMAGE_URLS.mercuryTextureSrc,
  [Bodies.VENUS.name]: IMAGE_URLS.venusTextureSrc,
  [Bodies.EARTH.name]: IMAGE_URLS.earthTextureSrc,
  [Bodies.LUNA.name]: IMAGE_URLS.lunaTextureSrc,
  [Bodies.MARS.name]: IMAGE_URLS.marsTextureSrc,
  [Bodies.JUPITER.name]: IMAGE_URLS.jupiterTextureSrc,
  [Bodies.SATURN.name]: IMAGE_URLS.saturnTextureSrc,
  [Bodies.URANUS.name]: IMAGE_URLS.uranusTextureSrc,
  [Bodies.NEPTUNE.name]: IMAGE_URLS.neptuneTextureSrc,
  [Bodies.CERES.name]: IMAGE_URLS.ceresTextureSrc,
  [Bodies.SATURN.rings![0].name]: IMAGE_URLS.saturnRingsTextureSrc,
};
