[build]
command = "yarn build"
functions = "functions"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = "/robots.txt"
to = "/assets/robots.txt"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
port = 19720
